### ISSUE TITLE
AppImage package

### ISSUE THREAD

**Issue by FrancescoCeruti** [FrancescoCeruti/linux-show-player#53]
It would be very useful to distribute an AppImage package, to provide a standalone version that can be used without installation on a reasonable number of GNU/Linux distributions, and remove the hassle of debian and family packaging :grimacing: 

### Tasks:
 - [x] a building script to simplify the entire process
 - [x] creating `virtualenv` with the required python version
 - [x] installing `linux-show-player` and pure-python extension in the `virtualenv`
 - [x] installing some of the "binary" modules needed by the extensions (python-cffi, python-rtimidi, ...) in `virtualev`
 - [x] including Qt5/PyQt5 and dependencies
 - [x] including GStreamer/python-gi and dependencies
 - [ ] test and make it work on a reasonable number of distributions

Unfortunately it seems that for some library it's a big mess :sob:

### References:
  * [AppImage wiki ](https://github.com/probonopd/appimagekit/wiki) _some outdated_

**Comment by probonopd** [comment]
Alternatively, you can save yourself a lot of work and convert pre-existing deb to an AppImage. However for this to work on more than just the newest distributions, it would be advisable to use debian oldstable or at least Ubuntu trusty or earlier (not xenial). Can you make such debs?

**Comment by FrancescoCeruti** [comment]
@probonopd 

> will not run on any distribution older than xenial. Is that acceptable?

It would be great if it works on older, I now some people use debian stable and I'd like to make newer versions available to them.

> we find a backport of Python 3.5

That's the idea, otherwise we can compile python3.5 on Jessie and verify if it works on newer systems.

**Comment by probonopd** [comment]
Yes. Compile on the oldest distribution it still compiles on, and use this build as the ingredients for what goes into the AppImage.

**Comment by FrancescoCeruti** [comment]
I've used [pyenv](https://github.com/yyuu/pyenv) to get the need version of python (3.5.3), it's really handy, so I hope it will not create some oddity with the AppImage

**Comment by FrancescoCeruti** [comment]
@probonopd 
So, I've completed most of the `tasks`, still `GStreamer` and `PyGObject` (python3-gi) are causing problems on "fresh" systems and on my ArchLinux (where `libpulsecommon-5.0.so` cannot be found despite being installed in the bundle).

I've tested on `Debian` and `Fedora` (live), both are crashing on `PyGObject` not able to found a "Gst namspace". Can it be related to some environment variable?

Plus, it seems that the build script works only on debian, on ubuntu virtualenv & pip cause some oddity with `site-packages` and `dist-packages` and the appimage doesn't works.

**Comment by probonopd** [comment]
You are aware that `apt-get` in the script installs only to the base system, not into the AppDir? So you need to copy Python and its libraries and modules manually from `/usr` to the AppImag and make sure it does not load Python modules from the outside by modifying `usr/lib/pythonX.X/sitecustomize.py` like this:

```
import sys,os
prefix = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(sys.path[0]))))
sys.path = [ prefix+s for s in sys.path if not s.startswith(prefix) ]
```

This works because `sys.path[0]` contains the directory from which Python was launched.

**Comment by FrancescoCeruti** [comment]
mmmh, `apt-get install` is used only to install build dependencies on the base system, the others packages are downloaded using `apt-get download` and "installed" locally using `dpkg.

About the python modules, they actually load correctly without `sitecustomize.py`, in fact I'm working with a virtual-environment. I've already tested sys.path and it contains the correct paths.

I'm going to change a few things to support python3.4 and see if I can solve the problem using the system python installation.

**Comment by FrancescoCeruti** [comment]
@probonopd I've update a few things, and now I'm building on Ubuntu 16.04, but I've almost the same problems.

So, `libpulsecommon-8.0.so` (instead of `libpulsecommon-5.0.so`) is located at `./usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so` but running `strace -eopen -f ./AppRun 2>&1 | grep "libpulsecommon-8.0.so"` I've find out that the folder is skipped

```
[pid 21206] open("./lib/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/i386-linux-gnu/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/i386-linux-gnu/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/i386-linux-gnu/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/i386-linux-gnu/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/x86_64-linux-gnu/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/x86_64-linux-gnu/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/x86_64-linux-gnu/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib/x86_64-linux-gnu/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib32/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib32/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib32/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib32/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib64/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib64/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib64/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("./lib64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/i386-linux-gnu/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/i386-linux-gnu/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/i386-linux-gnu/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/i386-linux-gnu/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/x86_64-linux-gnu/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/x86_64-linux-gnu/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/x86_64-linux-gnu/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib/x86_64-linux-gnu/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib32/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib32/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib32/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib32/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib64/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib64/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib64/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("../lib64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("/usr/lib/tls/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("/usr/lib/tls/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("/usr/lib/x86_64/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 21206] open("/usr/lib/libpulsecommon-8.0.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Any idea?

**Comment by probonopd** [comment]
Please move it from `./usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon*.so` to  `./usr/lib/x86_64-linux-gnu/`.

**Comment by FrancescoCeruti** [comment]
That's obviously works but I've few `<x86_64-linux-gnu>` sub-directories (some contains only data):

```
x86_64-linux-gnu/
├── alsa-lib
│   └── smixer
├── gio
│   └── modules
├── glib-2.0
├── gstreamer-1.0
├── gstreamer1.0
│   └── gstreamer-1.0
├── mesa
├── mesa-egl
└── pulseaudio
```

Are those not "visible" too?

And during my tests there are things, like the alsa modules, that are searched only in a specific location of the base system, like this one:

```
[pid 19266] open("/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by probonopd** [comment]
As of now, only `./usr/lib/x86_64-linux-gnu/` from the AppImage but not its subdirectories [get added](https://github.com/probonopd/AppImageKit/blob/5acfa80d10b2b27059ab2ae229e1e07baa2ecd98/AppRun.c#L121) to the `LD_LIBRARY_PATH` by AppRun.

Do you also have a copy of `libasound_module_pcm_pulse.so` in the AppImage`? What happens if you move it to `./usr/lib/x86_64-linux-gnu/` in the AppImage?

**Comment by FrancescoCeruti** [comment]
@probonopd Thanks for help, I've fixed the GStreamer problem using the `GI_TYPELIB_PATH` environment variable ... now let's hope that everything works on other distro ;)

**Comment by probonopd** [comment]
@FrancescoCeruti I can help with the testing on various distros, is the AppImage available for testing somewhere?

**Comment by FrancescoCeruti** [comment]
@probonopd that would be great! I've already successfully tested it on ubuntu 16.04 and 16.10, 64bit since I've not build a 32bit version yet.

You can download the AppImage here:
https://mega.nz/#!SoNTRZBa!Wtt8HgdP5JEU6qAG8xYmnmmpeinZg0iwFKBEXD9jl1A

You should run it with `--log debug` to get more info especially from modules/plugins, probably it will segfaults on exit, it's not directly related to the AppImage but to python garbage-collection an Qt.

**Comment by probonopd** [comment]
Fails on `ubuntu-14.04.1-desktop-amd64.iso` for me:

```
cannot load library libjack.so.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./lib/x86_64-linux-gnu/libjack.so.0)
```

Also, it seems to load gstreamer libraries from the base system (distribution) rather than from the AppImage:

```
(gst-plugin-scanner:5309): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstjack.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./lib/x86_64-linux-gnu/libjack.so.0)
```

Please move all libraries from subdirectories of `usr/lib/x86_64-linux-gnu/` and `usr/lib/` inside the AppImage to their respective parent directory, e.g., move `usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstjack.so` to `usr/lib/x86_64-linux-gnu/libgstjack.so`. The subdirectories do not get added to the `LD_LIBRARY_PATH` and hence are not found, which means that the system ones get loaded, which fails.

**Comment by FrancescoCeruti** [comment]
Mmmh, I doubt that il will work since the AppImage it's build on Ubuntu 16.04, isn't `version 'GLIBCXX_3.4.21' not found` the problem?

I can try to move `usr/lib/x86_64-linux-gnu/gstreamer-1.0/` to the parent, but GStreamer is already told to look there for it's plugins (via an environment variable set in the AppImage) and this may result in `gst-plugin-scanner` looking every file in `usr/lib/x86_64-linux-gnu/` to search for the plugins.

**Comment by probonopd** [comment]
>  the AppImage it's build on Ubuntu 16.04

Possibly building on an older version of Ubuntu and/or including libstdc++ in the AppImage might solve this.

**Comment by FrancescoCeruti** [comment]
Ok, so I'm back on debian jessie for building, but doesn't including `libstdc++` create problems? I've noticed that it's in the "excludelist" file.

**Comment by probonopd** [comment]
"It depends", it's worth a try but I am not sure about the outcome in this situation. The excludelist is tailored toward applications that are compiled on "old enough" target systems. The situation here is slightly different. May be worth a try but may well fail.

**Comment by FrancescoCeruti** [comment]
@probonopd I've included libstdc++, you can download the new AppImage here: https://mega.nz/#!L9cwlBzL!HRqUmVIZwfKl06-tDk-znIvooGMQr9mL5Q2sEhIF3S0

It's not a big deal If it still fail on systems older then Debian Jessie

**Comment by probonopd** [comment]
It launches on Ubuntu 16.04 but I just get an empty pane saying "Page 1" and nothing else. Is this how it should look?

**Comment by FrancescoCeruti** [comment]
Yes, you should be able to add audio files via the menu bar `edit->media cues->audio cue (from file)` and play them (click with the mouse), anyway if you launched it with `--log debug` and no "error" is printed, then it should be fine.

**Comment by probonopd** [comment]
This is what I am getting on a fresh Ubuntu 16.04 system:

```
me@host:~$ /home/me/Downloads/Linux_Show_Player-master-x86_64.AppImage --log debug
19:16:53.196 INFO:: Using en_US locale
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
19:16:53.400 DEBUG:: ACTION-CUES: Loaded "CollectionCue"
19:16:53.409 DEBUG:: ACTION-CUES: Loaded "CommandCue"
19:16:53.410 DEBUG:: ACTION-CUES: Loaded "IndexActionCue"
19:16:53.451 DEBUG:: ACTION-CUES: Loaded "MidiCue"
19:16:53.453 DEBUG:: ACTION-CUES: Loaded "SeekCue"
19:16:53.454 DEBUG:: ACTION-CUES: Loaded "StopAll"
19:16:53.456 DEBUG:: ACTION-CUES: Loaded "VolumeControl"
19:16:53.456 DEBUG:: MODULES: Loaded "ActionCues"

(gst-plugin-scanner:4030): GStreamer-WARNING **: Failed to load plugin '././/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopencv.so': /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0: undefined symbol: XRRGetMonitors

(gst-plugin-scanner:4030): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstclutter-3.0.so': ./lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)

(gst-plugin-scanner:4030): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoretracers.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoretracers.so: undefined symbol: gst_tracer_record_new

(gst-plugin-scanner:4030): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstximagesink.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstximagesink.so: undefined symbol: gst_navigation_message_new_event

(gst-plugin-scanner:4030): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstxvimagesink.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstxvimagesink.so: undefined symbol: gst_navigation_message_new_event
19:16:54.672 DEBUG:: MODULES: Loaded "GstBackend"
19:16:54.673 DEBUG:: MODULES: Loaded "MediaCueMenus"
19:16:54.718 DEBUG:: MODULES: Loaded "MediaInfo"
19:16:54.725 DEBUG:: MODULES: Loaded "Midi"
19:16:54.735 DEBUG:: MODULES: Loaded "Presets"
19:16:54.777 INFO:: REMOTE: Session started at ('127.0.1.1', 8070)
19:16:54.777 DEBUG:: MODULES: Loaded "Remote"
19:16:54.781 DEBUG:: MODULES: Loaded "ReplayGain"
19:16:54.784 DEBUG:: MODULES: Loaded "UriChanger"
19:16:54.802 DEBUG:: PLUGINS: Loaded "Controller"
19:16:54.805 DEBUG:: PLUGINS: Loaded "Synchronizer"
19:16:55.077 DEBUG:: PLUGINS: Loaded "Timecode"
19:16:55.079 DEBUG:: PLUGINS: Loaded "Triggers"
```

**Comment by FrancescoCeruti** [comment]
yeah, it's okay

**Comment by probonopd** [comment]
Maybe you'd like to consider to put something into that large grey area to make it clear to newcomers what to do... ;-)

**Comment by FrancescoCeruti** [comment]
@probonopd I'll take that in mind :)

Looks like I've fixed almost everything, now it's working even on Fedora. I've removed libstdc++ because of some errors, at this point I prefer support only "newer" distro than becoming mad to support them all :wink:

If you like to test it on other system here the link: https://mega.nz/#!mslFhYaC!rbfPa3lVlud2xuZua36u1ndU7xfIxPYJIKUB75b9AlQ

**Comment by probonopd** [comment]
Thanks. Looks good to me.
